export const projects = [
  {
    id: 1,
    NuxtImg: "/image/project-2.png",
    status: 'COMPLETED',
    name: "Abuja Gas Expansion",
    year: "2024",
    alt: "project ",
  },
  {
    id: 2,
    NuxtImg: "/image/project-1.png",
    status: 'ONGOING',
    name: "Abuja Gas Expansion",
    year: "2024",
    alt: "project",
  },
  {
    id: 3,
    NuxtImg: "/image/project-1.png",
    status: 'ONGOING',
    name: "Abuja Gas Expansion",
    year: "2024",
    alt: "project",
  },
  {
    id: 4,
    NuxtImg: "/image/project-1.png",
    status: 'ONGOING',
    name: "Abuja Gas Expansion",
    year: "2024",
    alt: "project",
  },
  {
    id: 5,
    NuxtImg: "/image/project-2.png",
    status: 'COMPLETED',
    name: "Abuja Gas Expansion",
    year: "2024",
    alt: "project",
  },
  {
    id: 6,
    NuxtImg: "/image/project-2.png",
    status: 'COMPLETED',
    name: "Abuja Gas Expansion",
    year: "2024",
    alt: "project",
  },
  {
    id: 7,
    NuxtImg: "/image/project-1.png",
    status: 'ONGOING',
    name: "Abuja Gas Expansion",
    year: "2024",
    alt: "project",
  },
  {
    id: 8,
    NuxtImg: "/image/project-1.png",
    status: 'ONGOING',
    name: "Abuja Gas Expansion",
    year: "2024",
    alt: "project",
  },
  {
    id: 9,
    NuxtImg: "/image/project-2.png",
    status: 'COMPLETED',
    name: "Abuja Gas Expansion",
    year: "2024",
    alt: "project",
  },
  {
    id: 10,
    NuxtImg: "/image/project-2.png",
    status: 'COMPLETED',
    name: "Abuja Gas Expansion",
    year: "2024",
    alt: "project",
  },
  {
    id: 11,
    NuxtImg: "/image/project-2.png",
    status: 'COMPLETED',
    name: "Abuja Gas Expansion",
    year: "2024",
    alt: "project",
  },
  {
    id: 12,
    NuxtImg: "/image/project-1.png",
    status: 'ONGOING',
    name: "Abuja Gas Expansion",
    year: "2024",
    alt: "project",
  },
];